"""
Tetrahedral Mesh v1: AI-Based FEA Mesh Generation for Hard Tissue (Femur)
=========================================================================
Topic #3: "AI based mesh generation for hard tissue"
Supervisor: Prof. Mahmuda Naznin (BUET CSE)
Collaborator: Prof. Tanvir R. Faisal (UL Lafayette, 4MLab)

Research Context:
  This thesis fills the MISSING STEP in the research group's pipeline:
  - SSDL Paper (Jamalia Sultana et al.): QCT → femur segmentation → 3D surface
  - THIS THESIS: 3D surface → FEA-quality tetrahedral volume mesh (AI-based)
  - FEA Surrogate Paper (Rabina Awal et al.): FE mesh features → fracture risk

Pipeline:
  1. Parse ANSYS CDB files (NBLOCK nodes + EBLOCK tetrahedral elements)
  2. Validate and analyze tetrahedral mesh structure
  3. Compute FEA mesh quality metrics per tetrahedron
  4. Visualize actual FE mesh (wireframe tetrahedra + surface mesh)
  5. Extract surface (boundary) mesh from volume mesh
  6. Prepare (surface → volume mesh) training pairs for AI mesh generation

Ground Truth Data:
  198 CDB files provided by collaborator — each containing a patient-specific
  femur mesh generated by lhpOpExporterAnsysCDB from QCT-based FE models.

Author: Tamim Saad (CSE 2018, BUET)
"""

# ============================================================
# SECTION 0: COLAB SETUP (Run this cell first)
# ============================================================
"""
# Uncomment and run in Google Colab:
!pip install ansys-mapdl-reader pyvista vtk plotly -q
!apt-get install -y xvfb libgl1-mesa-glx -q 2>/dev/null
!pip install pyvista[jupyter] -q
import os
os.environ['PYVISTA_OFF_SCREEN'] = 'true'
"""

# ============================================================
# SECTION 1: IMPORTS
# ============================================================
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from mpl_toolkits.mplot3d.art3d import Poly3DCollection
import seaborn as sns
import os
import glob
import re
import warnings
import time
from pathlib import Path
from collections import defaultdict, Counter
from itertools import combinations

warnings.filterwarnings('ignore')

# Optional imports with graceful fallback
USE_PYANSYS = False
try:
    from ansys.mapdl.reader import Archive
    USE_PYANSYS = True
    print("✅ ansys-mapdl-reader available")
except ImportError:
    print("⚠️ ansys-mapdl-reader not available, using custom parser")

USE_PYVISTA = False
try:
    import pyvista as pv
    USE_PYVISTA = True
    pv.set_plot_theme('document')
    print("✅ PyVista available")
except ImportError:
    print("⚠️ PyVista not available, using matplotlib fallback")

USE_PLOTLY = False
try:
    import plotly.graph_objects as go
    import plotly.express as px
    from plotly.subplots import make_subplots
    USE_PLOTLY = True
    print("✅ Plotly available")
except ImportError:
    print("⚠️ Plotly not available")

print("=" * 60)
print("🦴 Tetrahedral Mesh v1: AI-Based FEA Mesh Generation")
print("   Topic: AI based mesh generation for hard tissue")
print("=" * 60)

# ============================================================
# SECTION 2: CONFIGURATION
# ============================================================
CONFIG = {
    # Data path (Google Drive for Colab)
    'data_dir': '/content/drive/MyDrive/Thesis/Data',

    # Quality thresholds (standard FEA criteria)
    'ar_good': 3.0,        # Aspect ratio < 3 = good
    'ar_poor': 10.0,       # Aspect ratio > 10 = poor
    'sj_good': 0.5,        # Scaled Jacobian > 0.5 = good
    'sj_poor': 0.2,        # Scaled Jacobian < 0.2 = poor
    'skew_good': 0.25,     # Skewness < 0.25 = good
    'skew_poor': 0.75,     # Skewness > 0.75 = poor

    # Visualization settings
    'max_viz_elements': 5000,
    'fig_dpi': 150,
}


# ============================================================
# SECTION 3: CDB PARSER (NBLOCK + EBLOCK)
# ============================================================
class CDBParser:
    """
    Parse ANSYS CDB files to extract:
      - NBLOCK: Node coordinates (node_id, x, y, z)
      - EBLOCK: Tetrahedral element connectivity (4 node IDs per element)

    CDB files are generated by lhpOpExporterAnsysCDB from QCT-based FE models.
    Each file = one femur (left/right) from a patient.
    Naming: PatientID_left/right_bonemat.cdb
    """

    def __init__(self):
        self.all_data = {}

    def parse_file(self, file_path):
        """Parse a single CDB file. Try pyansys first, fallback to custom."""
        fname = os.path.basename(file_path)
        if USE_PYANSYS:
            try:
                return self._parse_pyansys(file_path, fname)
            except Exception as e:
                print(f"  ⚠️ pyansys failed for {fname}: {e}, using custom parser")
        return self._parse_custom(file_path, fname)

    def _parse_pyansys(self, file_path, fname):
        """Parse using ansys-mapdl-reader (official)."""
        archive = Archive(file_path)
        node_ids = archive.nnum
        nodes_arr = archive.nodes
        nodes_df = pd.DataFrame({
            'node_id': node_ids,
            'x': nodes_arr[:, 0], 'y': nodes_arr[:, 1], 'z': nodes_arr[:, 2]
        })
        elements = []
        if hasattr(archive, 'elem') and len(archive.elem) > 0:
            for elem in archive.elem:
                node_list = [n for n in elem[-1] if n > 0]
                if len(node_list) >= 4:
                    elements.append(tuple(node_list[:4]))

        metadata = self._build_metadata(fname, file_path, 'pyansys')
        print(f"  ✅ {fname}: {len(nodes_df)} nodes, {len(elements)} tetrahedra (pyansys)")
        return nodes_df, elements, metadata

    def _parse_custom(self, file_path, fname):
        """Custom parser for CDB files (robust fallback)."""
        nodes, elements = [], []
        in_nblock, in_eblock = False, False
        format_info = None

        with open(file_path, 'r', encoding='utf-8', errors='ignore') as f:
            lines = f.readlines()

        for i, line in enumerate(lines):
            ls = line.strip()

            # --- NBLOCK parsing ---
            if ls.startswith('NBLOCK'):
                in_nblock, in_eblock = True, False
                continue
            if in_nblock and ls.startswith('('):
                fmt = {}
                im = re.search(r'(\d+)i(\d+)', ls)
                if im:
                    fmt['iw'] = int(im.group(2))
                fm = re.search(r'(\d+)e(\d+)', ls)
                if fm:
                    fmt['fw'] = int(fm.group(2))
                format_info = fmt if fmt else None
                continue
            if in_nblock and ls and not ls.startswith('!') and not ls.startswith('/'):
                if ls.startswith('EBLOCK') or ls.startswith('-1') or ls.startswith('N,'):
                    in_nblock = False
                    if ls.startswith('EBLOCK'):
                        in_eblock = True
                    continue
                result = self._parse_node_line(line, ls, format_info)
                if result:
                    nodes.append(result)
                continue

            # --- EBLOCK parsing ---
            if ls.startswith('EBLOCK'):
                in_eblock, in_nblock = True, False
                continue
            if in_eblock and ls.startswith('('):
                continue
            if in_eblock:
                if ls.startswith('-1') or ls.startswith('NBLOCK') or \
                   ls.startswith('FINISH') or not ls:
                    in_eblock = False
                    continue
                elem = self._parse_element_line(ls)
                if elem:
                    elements.append(elem)

        nodes_df = pd.DataFrame(nodes, columns=['node_id', 'x', 'y', 'z']) if nodes else pd.DataFrame()
        metadata = self._build_metadata(fname, file_path, 'custom')
        print(f"  ✅ {fname}: {len(nodes_df)} nodes, {len(elements)} tetrahedra (custom)")
        return nodes_df, elements, metadata

    def _parse_node_line(self, raw_line, stripped, fmt):
        """Parse a single NBLOCK line (fixed-width or space-separated)."""
        if fmt and 'iw' in fmt and 'fw' in fmt:
            try:
                iw, fw = fmt['iw'], fmt['fw']
                offset = iw * 3
                nid = int(raw_line[:iw].strip())
                x = float(raw_line[offset:offset + fw].strip())
                y = float(raw_line[offset + fw:offset + 2 * fw].strip())
                z = float(raw_line[offset + 2 * fw:offset + 3 * fw].strip())
                return [nid, x, y, z]
            except (ValueError, IndexError):
                pass
        try:
            parts = stripped.split()
            if len(parts) >= 6:
                return [int(parts[0]), float(parts[3]), float(parts[4]), float(parts[5])]
        except (ValueError, IndexError):
            pass
        return None

    def _parse_element_line(self, line):
        """
        Parse EBLOCK line → tetrahedral element (4 node IDs).

        EBLOCK format: first 11 fields = metadata, field 9 = num_nodes,
        fields 12+ = node IDs.
        """
        try:
            parts = line.split()
            if len(parts) >= 11:
                num_nodes = int(parts[8]) if parts[8].isdigit() else 4
                node_start = 11
                if len(parts) >= node_start + 4:
                    node_ids = []
                    for j in range(min(num_nodes, len(parts) - node_start)):
                        p = parts[node_start + j]
                        if p.lstrip('-').isdigit() and int(p) > 0:
                            node_ids.append(int(p))
                    if len(node_ids) >= 4:
                        return tuple(node_ids[:4])
            elif len(parts) >= 8:
                node_ids = [int(p) for p in parts if p.lstrip('-').isdigit() and int(p) > 0]
                if len(node_ids) >= 4:
                    return tuple(node_ids[-4:])
        except (ValueError, IndexError):
            pass
        return None

    def _build_metadata(self, fname, file_path, parser_type):
        """Build metadata dict from filename."""
        parts = fname.replace('_bonemat.cdb', '').replace('_re', '').split('_')
        patient_id = parts[0] if parts else fname
        side = 'left' if 'left' in fname.lower() else ('right' if 'right' in fname.lower() else 'unknown')
        return {'parser': parser_type, 'file_path': file_path,
                'patient_id': patient_id, 'side': side}

    def parse_directory(self, directory):
        """Parse all CDB files in a directory."""
        cdb_files = sorted(glob.glob(os.path.join(directory, "*.cdb")))
        if not cdb_files:
            print(f"❌ No CDB files found in {directory}")
            return {}
        print(f"🔍 Found {len(cdb_files)} CDB files in {directory}")
        print("-" * 60)

        for fp in cdb_files:
            fname = os.path.basename(fp)
            nodes_df, elements, metadata = self.parse_file(fp)
            if not nodes_df.empty:
                self.all_data[fname] = {
                    'nodes_df': nodes_df, 'elements': elements, 'metadata': metadata
                }

        total_nodes = sum(len(d['nodes_df']) for d in self.all_data.values())
        total_elems = sum(len(d['elements']) for d in self.all_data.values())
        n_with_elem = sum(1 for d in self.all_data.values() if len(d['elements']) > 0)
        n_left = sum(1 for d in self.all_data.values() if d['metadata']['side'] == 'left')
        n_right = sum(1 for d in self.all_data.values() if d['metadata']['side'] == 'right')

        print("\n" + "=" * 60)
        print(f"📊 PARSING SUMMARY")
        print(f"  Files parsed:     {len(self.all_data)}")
        print(f"  With elements:    {n_with_elem}")
        print(f"  Left / Right:     {n_left} / {n_right}")
        print(f"  Total nodes:      {total_nodes:,}")
        print(f"  Total tetrahedra: {total_elems:,}")
        print(f"  Avg nodes/file:   {total_nodes // max(len(self.all_data), 1):,}")
        print(f"  Avg elems/file:   {total_elems // max(len(self.all_data), 1):,}")
        print("=" * 60)
        return self.all_data


# ============================================================
# SECTION 4: TETRAHEDRAL MESH ANALYSIS
# ============================================================
class TetrahedralMeshAnalyzer:
    """
    Analyze tetrahedral mesh structure from CDB data.
    Core analysis of tetrahedral finite elements — nodes + connectivity.
    """

    @staticmethod
    def validate_mesh(nodes_df, elements):
        """
        Validate tetrahedral mesh integrity.
        Checks: node references, element size, degenerate elements, volume.
        """
        if nodes_df.empty or not elements:
            return {'valid': False, 'reason': 'Empty data'}, []

        valid_nids = set(nodes_df['node_id'].astype(int).values)
        nid_to_xyz = {}
        for _, row in nodes_df.iterrows():
            nid_to_xyz[int(row['node_id'])] = np.array([row['x'], row['y'], row['z']])

        results = {
            'total_elements': len(elements), 'valid_elements': 0,
            'invalid_node_refs': 0, 'degenerate': 0, 'negative_volume': 0,
            'nodes_used': set(), 'orphan_nodes': 0,
        }
        valid_elements = []
        for elem in elements:
            if not all(nid in valid_nids for nid in elem[:4]):
                results['invalid_node_refs'] += 1
                continue
            pts = [nid_to_xyz[nid] for nid in elem[:4]]
            v0, v1, v2 = pts[1] - pts[0], pts[2] - pts[0], pts[3] - pts[0]
            det = np.dot(v0, np.cross(v1, v2))
            volume = abs(det) / 6.0
            if volume < 1e-15:
                results['degenerate'] += 1
                continue
            if det < 0:
                results['negative_volume'] += 1
            results['valid_elements'] += 1
            results['nodes_used'].update(elem[:4])
            valid_elements.append(elem)

        results['orphan_nodes'] = len(valid_nids - results['nodes_used'])
        results['nodes_used'] = len(results['nodes_used'])
        results['valid'] = results['valid_elements'] > 0
        return results, valid_elements

    @staticmethod
    def compute_mesh_stats(nodes_df, elements):
        """Compute overall mesh statistics."""
        if nodes_df.empty:
            return {}
        coords = nodes_df[['x', 'y', 'z']].values
        return {
            'num_nodes': len(nodes_df), 'num_elements': len(elements),
            'x_span_mm': coords[:, 0].ptp(), 'y_span_mm': coords[:, 1].ptp(),
            'z_span_mm': coords[:, 2].ptp(),
            'centroid': coords.mean(axis=0),
        }

    @staticmethod
    def build_connectivity(elements):
        """
        Build connectivity graph.
        Returns node-to-element map, element adjacency, face-to-element map.
        """
        node_to_elems = defaultdict(list)
        face_to_elems = defaultdict(list)

        for ei, elem in enumerate(elements):
            nodes = elem[:4]
            for nid in nodes:
                node_to_elems[nid].append(ei)
            faces = [
                frozenset([nodes[0], nodes[1], nodes[2]]),
                frozenset([nodes[0], nodes[1], nodes[3]]),
                frozenset([nodes[0], nodes[2], nodes[3]]),
                frozenset([nodes[1], nodes[2], nodes[3]]),
            ]
            for face in faces:
                face_to_elems[face].append(ei)

        adjacency = defaultdict(set)
        for face, elems in face_to_elems.items():
            if len(elems) == 2:
                adjacency[elems[0]].add(elems[1])
                adjacency[elems[1]].add(elems[0])

        return dict(node_to_elems), dict(adjacency), dict(face_to_elems)


# ============================================================
# SECTION 5: MESH QUALITY METRICS
# ============================================================
class MeshQualityAnalyzer:
    """
    FEA mesh quality metrics per tetrahedron.

    Metrics:
    - Volume (mm³)
    - Aspect Ratio: circumradius/inradius ratio (ideal = 1)
    - Scaled Jacobian: element distortion [-1, 1] (ideal = 1)
    - Skewness: deviation from ideal [0, 1] (ideal = 0)
    - Edge Ratio: max/min edge length (ideal = 1)
    - Min Dihedral Angle: smallest angle between faces
    """

    @staticmethod
    def compute_all_metrics(nodes_df, elements):
        """Compute quality metrics for all tetrahedra. Returns DataFrame."""
        if not elements or nodes_df.empty:
            return pd.DataFrame()

        nid_to_xyz = {}
        for _, row in nodes_df.iterrows():
            nid_to_xyz[int(row['node_id'])] = np.array([row['x'], row['y'], row['z']])

        records = []
        for ei, elem in enumerate(elements):
            try:
                pts = [nid_to_xyz[nid] for nid in elem[:4] if nid in nid_to_xyz]
                if len(pts) < 4:
                    continue
                m = MeshQualityAnalyzer._tet_metrics(*pts)
                if m:
                    m['elem_idx'] = ei
                    m['n0'], m['n1'], m['n2'], m['n3'] = elem[:4]
                    records.append(m)
            except (KeyError, ValueError):
                continue

        if not records:
            return pd.DataFrame()

        df = pd.DataFrame(records)
        df['quality_class'] = df.apply(
            lambda r: MeshQualityAnalyzer._classify(
                r['aspect_ratio'], r['scaled_jacobian'], r['skewness']), axis=1)
        return df

    @staticmethod
    def _tet_metrics(p0, p1, p2, p3):
        """Compute quality metrics for a single tetrahedron."""
        edges = [p1 - p0, p2 - p0, p3 - p0, p2 - p1, p3 - p1, p3 - p2]
        edge_lengths = np.array([np.linalg.norm(e) for e in edges])
        if np.any(edge_lengths < 1e-12):
            return None

        v0, v1, v2 = p1 - p0, p2 - p0, p3 - p0
        det_J = np.dot(v0, np.cross(v1, v2))
        volume = abs(det_J) / 6.0
        if volume < 1e-15:
            return None

        edge_ratio = edge_lengths.max() / edge_lengths.min()

        faces = [(p0, p1, p2), (p0, p1, p3), (p0, p2, p3), (p1, p2, p3)]
        face_areas = [0.5 * np.linalg.norm(np.cross(fb - fa, fc - fa))
                      for fa, fb, fc in faces]
        total_area = sum(face_areas)
        if total_area < 1e-15:
            return None

        inradius = 3.0 * volume / total_area
        aspect_ratio = edge_lengths.max() / (2.0 * np.sqrt(6) * inradius)

        l0, l1, l2 = np.linalg.norm(v0), np.linalg.norm(v1), np.linalg.norm(v2)
        if l0 * l1 * l2 < 1e-15:
            return None
        scaled_jac = np.clip(det_J / (l0 * l1 * l2 * np.sqrt(2)), -1.0, 1.0)

        mean_edge = edge_lengths.mean()
        v_ideal = mean_edge ** 3 / (6.0 * np.sqrt(2))
        skewness = 1.0 - min(volume / v_ideal, 1.0) if v_ideal > 0 else 1.0

        normals = [np.cross(fb - fa, fc - fa) for fa, fb, fc in faces]
        normals = [n / max(np.linalg.norm(n), 1e-12) for n in normals]
        angles = []
        for i in range(len(normals)):
            for j in range(i + 1, len(normals)):
                angles.append(np.degrees(np.arccos(np.clip(abs(np.dot(normals[i], normals[j])), -1, 1))))
        min_angle = min(angles) if angles else 0

        return {'volume': volume, 'aspect_ratio': aspect_ratio,
                'scaled_jacobian': scaled_jac, 'skewness': skewness,
                'edge_ratio': edge_ratio, 'min_angle': min_angle}

    @staticmethod
    def _classify(ar, sj, skew):
        """Classify element quality based on standard FEA thresholds."""
        votes = [0, 0, 0]
        if ar < CONFIG['ar_good']:   votes[0] += 1
        elif ar > CONFIG['ar_poor']: votes[2] += 1
        else:                        votes[1] += 1
        if sj > CONFIG['sj_good']:   votes[0] += 1
        elif sj < CONFIG['sj_poor']: votes[2] += 1
        else:                        votes[1] += 1
        if skew < CONFIG['skew_good']:  votes[0] += 1
        elif skew > CONFIG['skew_poor']:votes[2] += 1
        else:                           votes[1] += 1
        return ['good', 'acceptable', 'poor'][np.argmax(votes)]


# ============================================================
# SECTION 6: SURFACE EXTRACTION
# ============================================================
class SurfaceExtractor:
    """
    Extract surface (boundary) mesh from tetrahedral volume mesh.

    Surface = triangular faces belonging to ONLY ONE tetrahedron.
    Internal faces are shared by two tetrahedra.

    In the thesis pipeline:
    - Surface mesh → INPUT to the AI mesh generator
    - Volume mesh  → OUTPUT of the AI mesh generator (ground truth from CDB)
    """

    @staticmethod
    def extract_surface(elements):
        """
        Extract boundary faces.
        Returns: (surface_faces, surface_node_ids)
        """
        face_count = Counter()
        for elem in elements:
            nodes = elem[:4]
            for face in [
                tuple(sorted([nodes[0], nodes[1], nodes[2]])),
                tuple(sorted([nodes[0], nodes[1], nodes[3]])),
                tuple(sorted([nodes[0], nodes[2], nodes[3]])),
                tuple(sorted([nodes[1], nodes[2], nodes[3]])),
            ]:
                face_count[face] += 1

        surface_faces = [f for f, c in face_count.items() if c == 1]
        surface_nodes = set()
        for face in surface_faces:
            surface_nodes.update(face)
        return surface_faces, surface_nodes

    @staticmethod
    def get_surface_mesh(nodes_df, elements):
        """
        Get complete surface mesh data.
        Returns: (surface_nodes_df, surface_faces, stats_dict)
        """
        surface_faces, surface_nids = SurfaceExtractor.extract_surface(elements)
        surface_nodes_df = nodes_df[nodes_df['node_id'].isin(surface_nids)].copy()

        total_faces = len(elements) * 4
        stats = {
            'total_elements': len(elements),
            'surface_faces': len(surface_faces),
            'internal_faces': (total_faces - len(surface_faces)) // 2,
            'total_nodes': len(nodes_df),
            'surface_nodes': len(surface_nids),
            'interior_nodes': len(nodes_df) - len(surface_nids),
        }
        return surface_nodes_df, surface_faces, stats


# ============================================================
# SECTION 7: MESH VISUALIZATION
# ============================================================
class MeshVisualizer:
    """
    Visualize tetrahedral FE mesh — wireframe, surface, quality maps.
    """

    @staticmethod
    def plot_surface_mesh(nodes_df, surface_faces, title="Femur Surface Mesh", ax=None):
        """Plot triangulated surface mesh using matplotlib."""
        if ax is None:
            fig = plt.figure(figsize=(12, 10))
            ax = fig.add_subplot(111, projection='3d')

        nid_to_xyz = {}
        for _, row in nodes_df.iterrows():
            nid_to_xyz[int(row['node_id'])] = np.array([row['x'], row['y'], row['z']])

        triangles = []
        for face in surface_faces:
            pts = [nid_to_xyz.get(nid) for nid in face]
            if None not in pts:
                triangles.append(pts)

        if not triangles:
            print("⚠️ No valid triangles")
            return ax

        max_tris = CONFIG['max_viz_elements']
        if len(triangles) > max_tris:
            idx = np.random.choice(len(triangles), max_tris, replace=False)
            triangles = [triangles[i] for i in idx]

        poly = Poly3DCollection(triangles, alpha=0.3, linewidths=0.2,
                                edgecolors='steelblue')
        poly.set_facecolor('lightcyan')
        ax.add_collection3d(poly)

        all_pts = np.array([p for tri in triangles for p in tri])
        margin = 5
        ax.set_xlim([all_pts[:, 0].min() - margin, all_pts[:, 0].max() + margin])
        ax.set_ylim([all_pts[:, 1].min() - margin, all_pts[:, 1].max() + margin])
        ax.set_zlim([all_pts[:, 2].min() - margin, all_pts[:, 2].max() + margin])
        ax.set_xlabel('X (mm)'); ax.set_ylabel('Y (mm)'); ax.set_zlabel('Z (mm)')
        ax.set_title(title, fontsize=14, fontweight='bold')
        return ax

    @staticmethod
    def plot_surface_plotly(nodes_df, surface_faces, title="Femur Surface Mesh"):
        """Interactive 3D surface mesh with Plotly."""
        if not USE_PLOTLY:
            return MeshVisualizer.plot_surface_mesh(nodes_df, surface_faces, title)

        nid_to_xyz = {}
        for _, row in nodes_df.iterrows():
            nid_to_xyz[int(row['node_id'])] = [row['x'], row['y'], row['z']]

        surface_nids = set()
        for face in surface_faces:
            surface_nids.update(face)

        nid_to_idx = {}
        vertices = []
        for idx, nid in enumerate(sorted(surface_nids)):
            if nid in nid_to_xyz:
                nid_to_idx[nid] = idx
                vertices.append(nid_to_xyz[nid])
        vertices = np.array(vertices)

        i_idx, j_idx, k_idx = [], [], []
        for face in surface_faces:
            if all(n in nid_to_idx for n in face):
                i_idx.append(nid_to_idx[face[0]])
                j_idx.append(nid_to_idx[face[1]])
                k_idx.append(nid_to_idx[face[2]])

        fig = go.Figure(data=[go.Mesh3d(
            x=vertices[:, 0], y=vertices[:, 1], z=vertices[:, 2],
            i=i_idx, j=j_idx, k=k_idx,
            color='lightcyan', opacity=0.7, flatshading=True,
            lighting=dict(ambient=0.5, diffuse=0.8, specular=0.3),
            name='Surface Mesh'
        )])
        fig.update_layout(
            title=dict(text=title, font=dict(size=16)),
            scene=dict(xaxis_title='X (mm)', yaxis_title='Y (mm)',
                       zaxis_title='Z (mm)', aspectmode='data'),
            width=900, height=700)
        fig.show()
        return fig

    @staticmethod
    def plot_tetrahedral_wireframe(nodes_df, elements, title="Tetrahedral Wireframe",
                                   max_elements=500, ax=None):
        """Plot wireframe view of tetrahedral elements."""
        if ax is None:
            fig = plt.figure(figsize=(12, 10))
            ax = fig.add_subplot(111, projection='3d')

        nid_to_xyz = {}
        for _, row in nodes_df.iterrows():
            nid_to_xyz[int(row['node_id'])] = np.array([row['x'], row['y'], row['z']])

        n_show = min(max_elements, len(elements))
        indices = np.random.choice(len(elements), n_show, replace=False)

        for i in indices:
            elem = elements[i]
            pts = [nid_to_xyz.get(nid) for nid in elem[:4]]
            if None in pts:
                continue
            pts = np.array(pts)
            for e1, e2 in [(0,1),(0,2),(0,3),(1,2),(1,3),(2,3)]:
                ax.plot3D(*zip(pts[e1], pts[e2]), color='steelblue',
                         linewidth=0.3, alpha=0.4)

        ax.set_xlabel('X (mm)'); ax.set_ylabel('Y (mm)'); ax.set_zlabel('Z (mm)')
        ax.set_title(title, fontsize=14, fontweight='bold')
        return ax

    @staticmethod
    def plot_surface_vs_tetrahedral(nodes_df, elements, surface_faces, fname):
        """
        Side-by-side: Surface mesh (AI input) vs Volume mesh (AI output).
        """
        fig = plt.figure(figsize=(16, 7))

        # Left: Surface mesh (boundary faces = AI input)
        ax1 = fig.add_subplot(121, projection='3d')
        MeshVisualizer.plot_surface_mesh(nodes_df, surface_faces,
                                          title='Surface Mesh (AI Input)\nBoundary triangular faces', ax=ax1)

        # Right: Tetrahedral wireframe (volume mesh = AI output)
        ax2 = fig.add_subplot(122, projection='3d')
        MeshVisualizer.plot_tetrahedral_wireframe(nodes_df, elements,
                                                    title='Tetrahedral Volume Mesh (AI Output)\nNodes + element connectivity',
                                                    ax=ax2)

        fig.suptitle(f'{fname}', fontsize=14, fontweight='bold', y=1.02)
        plt.tight_layout()
        plt.savefig('surface_vs_volume_mesh.png', dpi=CONFIG['fig_dpi'], bbox_inches='tight')
        plt.show()
        return fig

    @staticmethod
    def plot_quality_distribution(quality_df, title="Mesh Quality Distribution"):
        """Plot quality metric distributions."""
        fig, axes = plt.subplots(2, 3, figsize=(18, 10))
        fig.suptitle(title, fontsize=16, fontweight='bold')

        # Aspect Ratio
        axes[0, 0].hist(quality_df['aspect_ratio'], bins=50, color='steelblue',
                        edgecolor='white', alpha=0.8)
        axes[0, 0].axvline(CONFIG['ar_good'], color='green', ls='--', label=f"Good < {CONFIG['ar_good']}")
        axes[0, 0].axvline(CONFIG['ar_poor'], color='red', ls='--', label=f"Poor > {CONFIG['ar_poor']}")
        axes[0, 0].set_xlabel('Aspect Ratio'); axes[0, 0].set_title('Aspect Ratio'); axes[0, 0].legend(fontsize=8)

        # Scaled Jacobian
        axes[0, 1].hist(quality_df['scaled_jacobian'], bins=50, color='teal',
                        edgecolor='white', alpha=0.8)
        axes[0, 1].axvline(CONFIG['sj_good'], color='green', ls='--', label=f"Good > {CONFIG['sj_good']}")
        axes[0, 1].axvline(CONFIG['sj_poor'], color='red', ls='--', label=f"Poor < {CONFIG['sj_poor']}")
        axes[0, 1].set_xlabel('Scaled Jacobian'); axes[0, 1].set_title('Scaled Jacobian'); axes[0, 1].legend(fontsize=8)

        # Skewness
        axes[0, 2].hist(quality_df['skewness'], bins=50, color='coral', edgecolor='white', alpha=0.8)
        axes[0, 2].axvline(CONFIG['skew_good'], color='green', ls='--', label=f"Good < {CONFIG['skew_good']}")
        axes[0, 2].axvline(CONFIG['skew_poor'], color='red', ls='--', label=f"Poor > {CONFIG['skew_poor']}")
        axes[0, 2].set_xlabel('Skewness'); axes[0, 2].set_title('Skewness'); axes[0, 2].legend(fontsize=8)

        # Volume
        axes[1, 0].hist(quality_df['volume'], bins=50, color='mediumpurple', edgecolor='white', alpha=0.8)
        axes[1, 0].set_xlabel('Volume (mm³)'); axes[1, 0].set_title('Element Volume')

        # Edge Ratio
        axes[1, 1].hist(quality_df['edge_ratio'], bins=50, color='goldenrod', edgecolor='white', alpha=0.8)
        axes[1, 1].set_xlabel('Edge Ratio'); axes[1, 1].set_title('Edge Ratio (max/min)')

        # Quality Pie
        cc = quality_df['quality_class'].value_counts()
        colors = {'good': '#2ecc71', 'acceptable': '#f39c12', 'poor': '#e74c3c'}
        axes[1, 2].pie(cc.values, labels=[f"{k}\n({v})" for k, v in cc.items()],
                       colors=[colors.get(k, 'gray') for k in cc.index],
                       autopct='%1.1f%%', startangle=90)
        axes[1, 2].set_title('Quality Classification')

        plt.tight_layout()
        plt.savefig('mesh_quality_distribution.png', dpi=CONFIG['fig_dpi'], bbox_inches='tight')
        plt.show()
        return fig


# ============================================================
# SECTION 8: DATASET ANALYSIS
# ============================================================
class DatasetAnalyzer:
    """Full dataset analysis across all CDB files."""

    @staticmethod
    def analyze_dataset(all_data):
        """Per-file statistics. Returns DataFrame."""
        records = []
        print("\n📊 DATASET ANALYSIS")
        print("=" * 60)

        qa = MeshQualityAnalyzer()
        se = SurfaceExtractor()

        for fname, data in all_data.items():
            nodes_df, elements = data['nodes_df'], data['elements']
            meta = data['metadata']
            stats = TetrahedralMeshAnalyzer.compute_mesh_stats(nodes_df, elements)
            _, _, surf_stats = se.get_surface_mesh(nodes_df, elements)
            qdf = qa.compute_all_metrics(nodes_df, elements)

            qs = {}
            if not qdf.empty:
                qs = {
                    'mean_ar': qdf['aspect_ratio'].mean(),
                    'mean_sj': qdf['scaled_jacobian'].mean(),
                    'mean_skew': qdf['skewness'].mean(),
                    'pct_good': (qdf['quality_class'] == 'good').mean() * 100,
                }

            records.append({
                'filename': fname, 'patient_id': meta['patient_id'], 'side': meta['side'],
                'num_nodes': stats.get('num_nodes', 0), 'num_tetrahedra': stats.get('num_elements', 0),
                'x_span_mm': stats.get('x_span_mm', 0), 'y_span_mm': stats.get('y_span_mm', 0),
                'z_span_mm': stats.get('z_span_mm', 0),
                'surface_faces': surf_stats.get('surface_faces', 0),
                'surface_nodes': surf_stats.get('surface_nodes', 0),
                'interior_nodes': surf_stats.get('interior_nodes', 0),
                **qs,
            })

        df = pd.DataFrame(records)
        print(f"\n{'Metric':<28} {'Min':>10} {'Mean':>10} {'Max':>10}")
        print("-" * 60)
        for col in ['num_nodes', 'num_tetrahedra', 'surface_faces', 'interior_nodes']:
            if col in df.columns:
                print(f"  {col:<26} {df[col].min():>10,.0f} {df[col].mean():>10,.0f} {df[col].max():>10,.0f}")
        return df

    @staticmethod
    def plot_overview(stats_df):
        """Dataset-level plots."""
        fig, axes = plt.subplots(2, 3, figsize=(18, 10))
        fig.suptitle('Dataset Overview — Femur CDB Files', fontsize=16, fontweight='bold')

        axes[0, 0].hist(stats_df['num_nodes'], bins=30, color='steelblue', edgecolor='white')
        axes[0, 0].set_xlabel('Nodes per file'); axes[0, 0].set_title('Node Count')

        axes[0, 1].hist(stats_df['num_tetrahedra'], bins=30, color='teal', edgecolor='white')
        axes[0, 1].set_xlabel('Tetrahedra per file'); axes[0, 1].set_title('Element Count')

        if 'surface_nodes' in stats_df.columns:
            axes[0, 2].bar(['Surface', 'Interior'],
                           [stats_df['surface_nodes'].mean(), stats_df['interior_nodes'].mean()],
                           color=['coral', 'mediumpurple'])
            axes[0, 2].set_title('Avg Surface vs Interior Nodes')

        if 'side' in stats_df.columns:
            sc = stats_df['side'].value_counts()
            axes[1, 0].bar(sc.index, sc.values, color=['#3498db', '#e74c3c'])
            axes[1, 0].set_title('Left vs Right')

        if all(c in stats_df.columns for c in ['x_span_mm', 'y_span_mm', 'z_span_mm']):
            axes[1, 1].boxplot([stats_df['x_span_mm'], stats_df['y_span_mm'], stats_df['z_span_mm']],
                               labels=['X', 'Y', 'Z'])
            axes[1, 1].set_ylabel('mm'); axes[1, 1].set_title('Bone Dimensions')

        if 'pct_good' in stats_df.columns:
            axes[1, 2].hist(stats_df['pct_good'], bins=20, color='#2ecc71', edgecolor='white')
            axes[1, 2].set_xlabel('% Good Quality'); axes[1, 2].set_title('Mesh Quality Distribution')

        plt.tight_layout()
        plt.savefig('dataset_overview.png', dpi=CONFIG['fig_dpi'], bbox_inches='tight')
        plt.show()
        return fig


# ============================================================
# SECTION 9: MESH REPRESENTATION (AI Input/Output)
# ============================================================
import torch
import torch.nn as nn
import torch.nn.functional as F
from torch.utils.data import Dataset, DataLoader
from sklearn.model_selection import KFold

DEVICE = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

# Model hyperparameters
MODEL_CONFIG = {
    'n_surface_pts': 2048,    # Fixed surface point count (input)
    'n_interior_pts': 4096,   # Fixed interior point count (target)
    'latent_dim': 512,        # Latent space dimension
    'dgcnn_k': 20,            # k-NN for DGCNN edge construction
    'batch_size': 2,          # Small batch for large meshes
    'epochs': 200,
    'lr': 1e-4,
    'lr_patience': 20,
    'weight_decay': 1e-5,
    'kl_weight': 0.001,       # KL divergence weight for CVAE
    'quality_weight': 0.1,    # Mesh quality loss weight
    'k_folds': 5,
}


class MeshRepresentation:
    """
    Convert raw CDB mesh data into fixed-size tensors for AI training.

    From each CDB file we extract:
      - INPUT:  Surface point cloud (n_surface_pts × 3)
      - TARGET: Interior node positions (n_interior_pts × 3)

    The AI learns: given surface geometry → predict where interior nodes go.
    Then scipy Delaunay tetrahedralizes the combined points into a tet mesh.
    """

    @staticmethod
    def normalize_points(points, return_params=True):
        """Center and scale to unit sphere."""
        centroid = points.mean(axis=0)
        centered = points - centroid
        scale = np.max(np.linalg.norm(centered, axis=1))
        if scale < 1e-10:
            scale = 1.0
        normalized = centered / scale
        if return_params:
            return normalized, centroid, scale
        return normalized

    @staticmethod
    def denormalize_points(points, centroid, scale):
        """Reverse normalization."""
        return points * scale + centroid

    @staticmethod
    def sample_or_pad(points, target_n):
        """Resample point cloud to exactly target_n points."""
        n = len(points)
        if n == 0:
            return np.zeros((target_n, 3))
        if n >= target_n:
            idx = np.random.choice(n, target_n, replace=False)
        else:
            idx = np.concatenate([
                np.arange(n),
                np.random.choice(n, target_n - n, replace=True)
            ])
        return points[idx]

    @staticmethod
    def prepare_training_pair(nodes_df, elements):
        """
        Convert one CDB mesh into (surface_pts, interior_pts) pair.

        1. Extract surface and interior nodes
        2. Normalize to unit sphere
        3. Resample to fixed counts
        """
        surface_faces, surface_nids = SurfaceExtractor.extract_surface(elements)
        all_nids = set(nodes_df['node_id'].astype(int).values)
        interior_nids = all_nids - surface_nids

        # Get coordinates
        nid_to_xyz = {}
        for _, row in nodes_df.iterrows():
            nid_to_xyz[int(row['node_id'])] = np.array([row['x'], row['y'], row['z']])

        surface_pts = np.array([nid_to_xyz[n] for n in surface_nids if n in nid_to_xyz])
        interior_pts = np.array([nid_to_xyz[n] for n in interior_nids if n in nid_to_xyz])

        if len(surface_pts) == 0 or len(interior_pts) == 0:
            return None

        # Normalize using surface centroid/scale (both surface and interior)
        all_pts = np.vstack([surface_pts, interior_pts])
        _, centroid, scale = MeshRepresentation.normalize_points(all_pts)
        surface_norm = (surface_pts - centroid) / scale
        interior_norm = (interior_pts - centroid) / scale

        # Resample to fixed size
        surface_fixed = MeshRepresentation.sample_or_pad(
            surface_norm, MODEL_CONFIG['n_surface_pts'])
        interior_fixed = MeshRepresentation.sample_or_pad(
            interior_norm, MODEL_CONFIG['n_interior_pts'])

        return {
            'surface': surface_fixed.astype(np.float32),
            'interior': interior_fixed.astype(np.float32),
            'centroid': centroid, 'scale': scale,
            'n_surface_orig': len(surface_pts),
            'n_interior_orig': len(interior_pts),
        }


# ============================================================
# SECTION 10: PYTORCH DATASET
# ============================================================
class TetrahedralMeshDataset(Dataset):
    """
    PyTorch Dataset for (surface → interior nodes) pairs.

    Each sample: surface point cloud (input) → interior point cloud (target).
    Data augmentation: random rotation, jitter, scaling for small dataset.
    """

    def __init__(self, all_data, augment=False):
        self.samples = []
        self.augment = augment
        self.filenames = []

        for fname, data in all_data.items():
            pair = MeshRepresentation.prepare_training_pair(
                data['nodes_df'], data['elements'])
            if pair is not None:
                self.samples.append(pair)
                self.filenames.append(fname)

        print(f"  Dataset: {len(self.samples)} valid samples "
              f"({'augmented' if augment else 'no augment'})")

    def __len__(self):
        return len(self.samples)

    def __getitem__(self, idx):
        sample = self.samples[idx]
        surface = torch.tensor(sample['surface'])
        interior = torch.tensor(sample['interior'])

        if self.augment:
            surface, interior = self._augment(surface, interior)

        return surface, interior, idx

    def _augment(self, surface, interior):
        """Data augmentation for small dataset (198 samples)."""
        # Random rotation around Z-axis (anatomically meaningful)
        angle = np.random.uniform(0, 2 * np.pi)
        cos_a, sin_a = np.cos(angle), np.sin(angle)
        rot = torch.tensor([
            [cos_a, -sin_a, 0],
            [sin_a,  cos_a, 0],
            [0,      0,     1]
        ], dtype=torch.float32)
        surface = surface @ rot.T
        interior = interior @ rot.T

        # Random scaling (±5%)
        s = 1.0 + np.random.uniform(-0.05, 0.05)
        surface = surface * s
        interior = interior * s

        # Random jitter on surface only (small noise)
        surface = surface + torch.randn_like(surface) * 0.002

        return surface, interior


# ============================================================
# SECTION 11: MODEL — DGCNN ENCODER (SOTA for surface geometry)
# ============================================================
"""
Architecture choices based on 2024-2025 mesh generation research:

1. DGCNN (Dynamic Graph CNN) encoder — Wang et al. 2019, widely used in 2024
   - Builds dynamic k-NN graph in feature space
   - EdgeConv captures local geometric patterns
   - Better than PointNet (ignores local structure) and PointNet++ (static groups)
   - Chosen because surface mesh has rich local geometric features

2. Conditional VAE decoder — for generative interior node prediction
   - VAE provides regularized latent space (good for 198 samples)
   - Conditional on surface features
   - Generates varied but valid interior distributions

3. DefTet-inspired post-processing — Gao et al. (NVIDIA)
   - Delaunay tetrahedralization of predicted points
   - Quality-aware mesh refinement
"""


def knn(x, k):
    """Compute k-nearest neighbors in feature space."""
    inner = -2 * torch.matmul(x.transpose(2, 1), x)
    xx = torch.sum(x ** 2, dim=1, keepdim=True)
    pairwise_distance = -xx - inner - xx.transpose(2, 1)
    idx = pairwise_distance.topk(k=k, dim=-1)[1]
    return idx


def get_graph_feature(x, k=20, idx=None):
    """Construct edge features for DGCNN."""
    batch_size, num_dims, num_points = x.size()
    device = x.device

    if idx is None:
        idx = knn(x, k=k)

    idx_base = torch.arange(0, batch_size, device=device).view(-1, 1, 1) * num_points
    idx = idx + idx_base
    idx = idx.view(-1)

    x = x.transpose(2, 1).contiguous()
    feature = x.view(batch_size * num_points, -1)[idx, :]
    feature = feature.view(batch_size, num_points, k, num_dims)
    x = x.view(batch_size, num_points, 1, num_dims).repeat(1, 1, k, 1)

    # Edge feature = [neighbor - center, center]
    feature = torch.cat((feature - x, x), dim=3).permute(0, 3, 1, 2).contiguous()
    return feature


class DGCNNEncoder(nn.Module):
    """
    Dynamic Graph CNN encoder for surface point clouds.

    Builds dynamic k-NN graph in feature space at each layer,
    applies EdgeConv to capture local geometric patterns.
    Outputs a global feature vector encoding surface geometry.

    Reference: Wang et al., "Dynamic Graph CNN for Learning on Point Clouds"
    """

    def __init__(self, input_dim=3, output_dim=512, k=20):
        super().__init__()
        self.k = k

        # EdgeConv layers with increasing feature dims
        self.conv1 = nn.Sequential(
            nn.Conv2d(input_dim * 2, 64, 1, bias=False),
            nn.BatchNorm2d(64), nn.LeakyReLU(0.2))
        self.conv2 = nn.Sequential(
            nn.Conv2d(64 * 2, 64, 1, bias=False),
            nn.BatchNorm2d(64), nn.LeakyReLU(0.2))
        self.conv3 = nn.Sequential(
            nn.Conv2d(64 * 2, 128, 1, bias=False),
            nn.BatchNorm2d(128), nn.LeakyReLU(0.2))
        self.conv4 = nn.Sequential(
            nn.Conv2d(128 * 2, 256, 1, bias=False),
            nn.BatchNorm2d(256), nn.LeakyReLU(0.2))

        # Aggregate all EdgeConv outputs
        self.conv5 = nn.Sequential(
            nn.Conv1d(64 + 64 + 128 + 256, output_dim, 1, bias=False),
            nn.BatchNorm1d(output_dim), nn.LeakyReLU(0.2))

    def forward(self, x):
        """
        x: (B, 3, N) surface points
        returns: (B, output_dim) global feature
        """
        batch_size = x.size(0)

        # EdgeConv blocks
        x1 = self.conv1(get_graph_feature(x, k=self.k))
        x1 = x1.max(dim=-1)[0]

        x2 = self.conv2(get_graph_feature(x1, k=self.k))
        x2 = x2.max(dim=-1)[0]

        x3 = self.conv3(get_graph_feature(x2, k=self.k))
        x3 = x3.max(dim=-1)[0]

        x4 = self.conv4(get_graph_feature(x3, k=self.k))
        x4 = x4.max(dim=-1)[0]

        # Concatenate multi-scale features
        x = torch.cat((x1, x2, x3, x4), dim=1)
        x = self.conv5(x)

        # Global max + avg pooling
        x_max = F.adaptive_max_pool1d(x, 1).view(batch_size, -1)
        x_avg = F.adaptive_avg_pool1d(x, 1).view(batch_size, -1)

        return torch.cat((x_max, x_avg), dim=1)  # (B, output_dim * 2)


# ============================================================
# SECTION 12: MODEL — CVAE DECODER (Interior Node Generation)
# ============================================================
class InteriorNodeDecoder(nn.Module):
    """
    Conditional decoder: latent vector → interior node positions.

    Uses FoldingNet-inspired approach: deforms a template point distribution
    conditioned on surface features to predict interior node locations.
    """

    def __init__(self, latent_dim=512, condition_dim=1024, n_points=4096):
        super().__init__()
        self.n_points = n_points

        # Generate template grid in 3D (initial point distribution)
        self.register_buffer('template',
            self._create_3d_template(n_points))

        # Folding network: template + condition → deformed points
        total_in = 3 + latent_dim + condition_dim
        self.fold1 = nn.Sequential(
            nn.Linear(total_in, 512), nn.ReLU(),
            nn.Linear(512, 512), nn.ReLU(),
            nn.Linear(512, 256), nn.ReLU(),
            nn.Linear(256, 3))

        self.fold2 = nn.Sequential(
            nn.Linear(3 + latent_dim + condition_dim, 512), nn.ReLU(),
            nn.Linear(512, 512), nn.ReLU(),
            nn.Linear(512, 256), nn.ReLU(),
            nn.Linear(256, 3))

    def _create_3d_template(self, n_points):
        """Create initial 3D point distribution (uniform in unit sphere)."""
        points = []
        while len(points) < n_points:
            p = np.random.randn(n_points * 2, 3)
            norms = np.linalg.norm(p, axis=1, keepdims=True)
            p = p / norms  # on unit sphere
            r = np.random.uniform(0, 1, (len(p), 1)) ** (1/3)  # uniform in volume
            p = p * r
            points.extend(p.tolist())
        points = np.array(points[:n_points], dtype=np.float32)
        return torch.tensor(points)

    def forward(self, z, condition):
        """
        z: (B, latent_dim) sampled latent
        condition: (B, condition_dim) surface features
        returns: (B, n_points, 3) predicted interior positions
        """
        B = z.size(0)
        template = self.template.unsqueeze(0).expand(B, -1, -1)  # (B, N, 3)

        # Expand z and condition to match points
        z_exp = z.unsqueeze(1).expand(-1, self.n_points, -1)
        c_exp = condition.unsqueeze(1).expand(-1, self.n_points, -1)

        # First folding
        inp1 = torch.cat([template, z_exp, c_exp], dim=2)
        fold1_out = self.fold1(inp1)

        # Second folding (refinement)
        inp2 = torch.cat([fold1_out, z_exp, c_exp], dim=2)
        fold2_out = self.fold2(inp2)

        return fold2_out


class SurfaceToVolumeCVAE(nn.Module):
    """
    Conditional Variational Autoencoder for mesh generation.

    Architecture (2024-2025 SOTA components):
    - Encoder: DGCNN (captures local surface geometry via dynamic graph)
    - Latent: VAE with surface-conditioned prior (handles 198 sample dataset)
    - Decoder: FoldingNet-style (deforms template → interior points)

    Pipeline:
    Surface points → DGCNN → surface features
                           → μ, σ (VAE latent)
                           → sample z
                           → Decoder(z, surface_features) → interior points
    """

    def __init__(self):
        super().__init__()
        k = MODEL_CONFIG['dgcnn_k']
        latent_dim = MODEL_CONFIG['latent_dim']
        n_interior = MODEL_CONFIG['n_interior_pts']
        encoder_out = 512 * 2  # DGCNN outputs max+avg pooling

        # Surface encoder (DGCNN — SOTA for point cloud feature extraction)
        self.encoder = DGCNNEncoder(input_dim=3, output_dim=512, k=k)

        # VAE latent space
        self.fc_mu = nn.Linear(encoder_out, latent_dim)
        self.fc_logvar = nn.Linear(encoder_out, latent_dim)

        # Interior point decoder (FoldingNet-style)
        self.decoder = InteriorNodeDecoder(
            latent_dim=latent_dim, condition_dim=encoder_out,
            n_points=n_interior)

    def encode(self, surface_pts):
        """Encode surface → features + latent distribution."""
        # surface_pts: (B, N, 3) → transpose to (B, 3, N) for DGCNN
        x = surface_pts.transpose(1, 2)
        features = self.encoder(x)  # (B, 1024)
        mu = self.fc_mu(features)
        logvar = self.fc_logvar(features)
        return features, mu, logvar

    def reparameterize(self, mu, logvar):
        """VAE reparameterization trick."""
        if self.training:
            std = torch.exp(0.5 * logvar)
            eps = torch.randn_like(std)
            return mu + eps * std
        return mu

    def decode(self, z, condition):
        """Decode latent + condition → interior points."""
        return self.decoder(z, condition)

    def forward(self, surface_pts):
        """Full forward: surface → interior points."""
        features, mu, logvar = self.encode(surface_pts)
        z = self.reparameterize(mu, logvar)
        interior_pred = self.decode(z, features)
        return interior_pred, mu, logvar


# ============================================================
# SECTION 13: LOSS FUNCTIONS & EVALUATION
# ============================================================
def chamfer_distance(pred, target):
    """
    Chamfer Distance between two point clouds.
    CD = mean(min_dist(pred→target)) + mean(min_dist(target→pred))
    """
    # pred: (B, N, 3), target: (B, M, 3)
    diff = pred.unsqueeze(2) - target.unsqueeze(1)  # (B, N, M, 3)
    dist = torch.sum(diff ** 2, dim=-1)              # (B, N, M)

    min_pred_to_target = dist.min(dim=2)[0].mean(dim=1)  # (B,)
    min_target_to_pred = dist.min(dim=1)[0].mean(dim=1)  # (B,)

    return (min_pred_to_target + min_target_to_pred).mean()


def earth_movers_distance_approx(pred, target, n_iter=50):
    """
    Approximate EMD via iterative closest point matching.
    More accurate than Chamfer but slower.
    """
    B, N, D = pred.shape
    _, M, _ = target.shape

    # Use Chamfer as approximation when M != N
    if N != M:
        return chamfer_distance(pred, target)

    # Sinkhorn-like approximation
    diff = pred.unsqueeze(2) - target.unsqueeze(1)
    cost = torch.sum(diff ** 2, dim=-1)  # (B, N, M)

    # Greedy assignment approximation
    total = 0
    for b in range(B):
        c = cost[b].clone()
        assignment_cost = 0
        for _ in range(min(N, M)):
            min_val, min_idx = c.min(dim=1)
            row_idx = min_val.argmin()
            col_idx = min_idx[row_idx]
            assignment_cost += c[row_idx, col_idx]
            c[row_idx, :] = float('inf')
            c[:, col_idx] = float('inf')
        total += assignment_cost / min(N, M)
    return total / B


class MeshGenerationLoss(nn.Module):
    """
    Combined loss for mesh generation:
    1. Chamfer Distance (primary — point distribution accuracy)
    2. KL Divergence (VAE regularization — prevents overfitting on 198 samples)
    3. Density Uniformity (encourages evenly distributed interior nodes)
    """

    def __init__(self):
        super().__init__()
        self.kl_weight = MODEL_CONFIG['kl_weight']
        self.quality_weight = MODEL_CONFIG['quality_weight']

    def forward(self, pred, target, mu, logvar):
        # Chamfer Distance
        cd = chamfer_distance(pred, target)

        # KL Divergence
        kl = -0.5 * torch.mean(1 + logvar - mu.pow(2) - logvar.exp())

        # Density uniformity: penalize clustering via nearest-neighbor variance
        diff = pred.unsqueeze(2) - pred.unsqueeze(1)
        self_dist = torch.sum(diff ** 2, dim=-1)
        self_dist = self_dist + torch.eye(pred.size(1), device=pred.device).unsqueeze(0) * 1e6
        nn_dist = self_dist.min(dim=2)[0]  # (B, N)
        density_loss = nn_dist.std(dim=1).mean()

        total = cd + self.kl_weight * kl + self.quality_weight * density_loss

        return total, {'chamfer': cd.item(), 'kl': kl.item(),
                       'density': density_loss.item(), 'total': total.item()}


class MeshGenerationEvaluator:
    """Evaluate generated mesh quality vs ground truth."""

    @staticmethod
    def evaluate_generated_mesh(pred_interior, gt_interior, surface_pts,
                                 centroid, scale):
        """
        Full evaluation of generated interior nodes.
        Combines predicted interior + surface → Delaunay → tet mesh → quality.
        """
        from scipy.spatial import Delaunay

        # Denormalize
        pred_pts = pred_interior * scale + centroid
        gt_pts = gt_interior * scale + centroid
        surf_pts = surface_pts * scale + centroid

        metrics = {}

        # 1. Chamfer Distance (normalized)
        pred_t = torch.tensor(pred_pts).unsqueeze(0).float()
        gt_t = torch.tensor(gt_pts).unsqueeze(0).float()
        metrics['chamfer_distance'] = chamfer_distance(pred_t, gt_t).item()

        # 2. Generate tetrahedral mesh from predicted interior + surface
        all_pts = np.vstack([surf_pts, pred_pts])
        try:
            tri = Delaunay(all_pts)
            gen_elements = [tuple(simplex) for simplex in tri.simplices]
            metrics['generated_elements'] = len(gen_elements)

            # Create nodes_df for quality analysis
            nodes_df = pd.DataFrame({
                'node_id': range(len(all_pts)),
                'x': all_pts[:, 0], 'y': all_pts[:, 1], 'z': all_pts[:, 2]
            })

            # 3. Compute quality metrics on generated mesh
            qdf = MeshQualityAnalyzer.compute_all_metrics(nodes_df, gen_elements)
            if not qdf.empty:
                metrics['mean_aspect_ratio'] = qdf['aspect_ratio'].mean()
                metrics['mean_scaled_jacobian'] = qdf['scaled_jacobian'].mean()
                metrics['mean_skewness'] = qdf['skewness'].mean()
                metrics['pct_good'] = (qdf['quality_class'] == 'good').mean() * 100
                metrics['pct_poor'] = (qdf['quality_class'] == 'poor').mean() * 100
        except Exception as e:
            metrics['delaunay_error'] = str(e)

        return metrics


# ============================================================
# SECTION 14: TRAINING PIPELINE
# ============================================================
class Trainer:
    """Training pipeline for SurfaceToVolumeCVAE."""

    def __init__(self, model, train_loader, val_loader):
        self.model = model.to(DEVICE)
        self.criterion = MeshGenerationLoss()
        self.optimizer = torch.optim.AdamW(
            model.parameters(), lr=MODEL_CONFIG['lr'],
            weight_decay=MODEL_CONFIG['weight_decay'])
        self.scheduler = torch.optim.lr_scheduler.ReduceLROnPlateau(
            self.optimizer, patience=MODEL_CONFIG['lr_patience'],
            factor=0.5, min_lr=1e-6)
        self.train_loader = train_loader
        self.val_loader = val_loader
        self.history = {'train_loss': [], 'val_loss': [],
                        'train_cd': [], 'val_cd': []}

    def train_epoch(self):
        self.model.train()
        total_loss, total_cd, n = 0, 0, 0
        for surface, interior, _ in self.train_loader:
            surface = surface.to(DEVICE)
            interior = interior.to(DEVICE)

            pred, mu, logvar = self.model(surface)
            loss, details = self.criterion(pred, interior, mu, logvar)

            self.optimizer.zero_grad()
            loss.backward()
            torch.nn.utils.clip_grad_norm_(self.model.parameters(), 1.0)
            self.optimizer.step()

            total_loss += details['total'] * surface.size(0)
            total_cd += details['chamfer'] * surface.size(0)
            n += surface.size(0)

        return total_loss / n, total_cd / n

    @torch.no_grad()
    def validate_epoch(self):
        self.model.eval()
        total_loss, total_cd, n = 0, 0, 0
        for surface, interior, _ in self.val_loader:
            surface = surface.to(DEVICE)
            interior = interior.to(DEVICE)

            pred, mu, logvar = self.model(surface)
            loss, details = self.criterion(pred, interior, mu, logvar)

            total_loss += details['total'] * surface.size(0)
            total_cd += details['chamfer'] * surface.size(0)
            n += surface.size(0)

        return total_loss / n, total_cd / n

    def train(self):
        best_val = float('inf')
        patience_counter = 0
        best_state = None

        print(f"\n  Training on {DEVICE} | "
              f"{sum(p.numel() for p in self.model.parameters()):,} parameters")

        for epoch in range(MODEL_CONFIG['epochs']):
            train_loss, train_cd = self.train_epoch()
            val_loss, val_cd = self.validate_epoch()

            self.history['train_loss'].append(train_loss)
            self.history['val_loss'].append(val_loss)
            self.history['train_cd'].append(train_cd)
            self.history['val_cd'].append(val_cd)

            self.scheduler.step(val_loss)

            if val_loss < best_val:
                best_val = val_loss
                patience_counter = 0
                best_state = {k: v.cpu().clone()
                              for k, v in self.model.state_dict().items()}
            else:
                patience_counter += 1

            if (epoch + 1) % 10 == 0 or epoch == 0:
                lr = self.optimizer.param_groups[0]['lr']
                print(f"    Epoch {epoch+1:3d} | Train CD: {train_cd:.6f} | "
                      f"Val CD: {val_cd:.6f} | LR: {lr:.1e}")

            if patience_counter >= 30:
                print(f"    Early stopping at epoch {epoch+1}")
                break

        if best_state:
            self.model.load_state_dict(best_state)
        return self.history


def run_kfold_training(all_data):
    """K-Fold cross-validation training."""
    print("\n" + "=" * 60)
    print("🧠 K-FOLD CROSS-VALIDATION TRAINING")
    print("=" * 60)

    # Prepare full dataset (no augmentation for splitting)
    full_dataset = TetrahedralMeshDataset(all_data, augment=False)
    n_samples = len(full_dataset)

    if n_samples < MODEL_CONFIG['k_folds']:
        print(f"  ⚠️ Only {n_samples} samples, reducing folds")
        MODEL_CONFIG['k_folds'] = min(n_samples, 3)

    kf = KFold(n_splits=MODEL_CONFIG['k_folds'], shuffle=True, random_state=42)
    indices = list(range(n_samples))

    all_fold_results = []

    for fold, (train_idx, val_idx) in enumerate(kf.split(indices)):
        print(f"\n{'='*50}")
        print(f"  FOLD {fold+1}/{MODEL_CONFIG['k_folds']} "
              f"(train={len(train_idx)}, val={len(val_idx)})")
        print(f"{'='*50}")

        # Create fold datasets
        train_ds = TetrahedralMeshDataset.__new__(TetrahedralMeshDataset)
        train_ds.samples = [full_dataset.samples[i] for i in train_idx]
        train_ds.filenames = [full_dataset.filenames[i] for i in train_idx]
        train_ds.augment = True

        val_ds = TetrahedralMeshDataset.__new__(TetrahedralMeshDataset)
        val_ds.samples = [full_dataset.samples[i] for i in val_idx]
        val_ds.filenames = [full_dataset.filenames[i] for i in val_idx]
        val_ds.augment = False

        train_loader = DataLoader(train_ds, MODEL_CONFIG['batch_size'],
                                  shuffle=True, drop_last=True)
        val_loader = DataLoader(val_ds, MODEL_CONFIG['batch_size'])

        # Create model
        model = SurfaceToVolumeCVAE()
        trainer = Trainer(model, train_loader, val_loader)
        history = trainer.train()

        # Evaluate on validation set
        fold_metrics = evaluate_fold(model, val_ds)
        fold_metrics['history'] = history
        fold_metrics['fold'] = fold + 1
        all_fold_results.append(fold_metrics)

    # Print summary
    print("\n" + "=" * 60)
    print("📊 K-FOLD RESULTS SUMMARY")
    print("=" * 60)
    val_cds = [r['mean_chamfer'] for r in all_fold_results]
    print(f"  Chamfer Distance: {np.mean(val_cds):.6f} ± {np.std(val_cds):.6f}")

    if all(r.get('mean_ar') is not None for r in all_fold_results):
        val_ars = [r['mean_ar'] for r in all_fold_results]
        val_sjs = [r['mean_sj'] for r in all_fold_results]
        val_goods = [r['pct_good'] for r in all_fold_results]
        print(f"  Aspect Ratio:     {np.mean(val_ars):.3f} ± {np.std(val_ars):.3f}")
        print(f"  Scaled Jacobian:  {np.mean(val_sjs):.3f} ± {np.std(val_sjs):.3f}")
        print(f"  % Good quality:   {np.mean(val_goods):.1f}% ± {np.std(val_goods):.1f}%")

    return all_fold_results


@torch.no_grad()
def evaluate_fold(model, val_ds):
    """Evaluate a trained model on validation set."""
    model.eval()
    evaluator = MeshGenerationEvaluator()
    all_metrics = []

    for i in range(len(val_ds)):
        sample = val_ds.samples[i]
        surface = torch.tensor(sample['surface']).unsqueeze(0).to(DEVICE)
        pred, _, _ = model(surface)
        pred_np = pred.cpu().numpy()[0]

        metrics = evaluator.evaluate_generated_mesh(
            pred_np, sample['interior'], sample['surface'],
            sample['centroid'], sample['scale'])
        all_metrics.append(metrics)

    result = {'mean_chamfer': np.mean([m['chamfer_distance'] for m in all_metrics])}
    if all('mean_aspect_ratio' in m for m in all_metrics):
        result['mean_ar'] = np.mean([m['mean_aspect_ratio'] for m in all_metrics])
        result['mean_sj'] = np.mean([m['mean_scaled_jacobian'] for m in all_metrics])
        result['pct_good'] = np.mean([m.get('pct_good', 0) for m in all_metrics])
    result['all_metrics'] = all_metrics
    return result


# ============================================================
# SECTION 15: RESULTS VISUALIZATION
# ============================================================
class ResultsVisualizer:
    """Visualize training results and generated meshes."""

    @staticmethod
    def plot_training_curves(fold_results):
        """Plot training/validation loss curves across folds."""
        n_folds = len(fold_results)
        fig, axes = plt.subplots(1, 2, figsize=(14, 5))
        fig.suptitle('Training Curves (K-Fold CV)', fontsize=14, fontweight='bold')

        for fr in fold_results:
            h = fr['history']
            fold_n = fr['fold']
            axes[0].plot(h['train_loss'], alpha=0.5, label=f'Fold {fold_n} train')
            axes[0].plot(h['val_loss'], alpha=0.8, linestyle='--',
                         label=f'Fold {fold_n} val')
            axes[1].plot(h['train_cd'], alpha=0.5, label=f'Fold {fold_n} train')
            axes[1].plot(h['val_cd'], alpha=0.8, linestyle='--',
                         label=f'Fold {fold_n} val')

        axes[0].set_xlabel('Epoch'); axes[0].set_ylabel('Total Loss')
        axes[0].set_title('Total Loss'); axes[0].legend(fontsize=7)
        axes[0].set_yscale('log')

        axes[1].set_xlabel('Epoch'); axes[1].set_ylabel('Chamfer Distance')
        axes[1].set_title('Chamfer Distance'); axes[1].legend(fontsize=7)
        axes[1].set_yscale('log')

        plt.tight_layout()
        plt.savefig('training_curves.png', dpi=CONFIG['fig_dpi'], bbox_inches='tight')
        plt.show()

    @staticmethod
    def plot_generated_vs_ground_truth(model, dataset, n_samples=3):
        """Visualize generated interior points vs ground truth."""
        model.eval()
        fig = plt.figure(figsize=(6 * n_samples, 10))

        for i in range(min(n_samples, len(dataset))):
            sample = dataset.samples[i]
            surface = torch.tensor(sample['surface']).unsqueeze(0).to(DEVICE)

            with torch.no_grad():
                pred, _, _ = model(surface)
            pred_np = pred.cpu().numpy()[0]

            # Top row: Ground truth
            ax1 = fig.add_subplot(2, n_samples, i + 1, projection='3d')
            ax1.scatter(sample['surface'][:, 0], sample['surface'][:, 1],
                       sample['surface'][:, 2], s=0.3, c='steelblue', alpha=0.3,
                       label='Surface')
            ax1.scatter(sample['interior'][:, 0], sample['interior'][:, 1],
                       sample['interior'][:, 2], s=0.5, c='coral', alpha=0.5,
                       label='Interior (GT)')
            ax1.set_title(f'Ground Truth ({dataset.filenames[i][:15]})',
                         fontsize=9)
            ax1.legend(fontsize=6)

            # Bottom row: Generated
            ax2 = fig.add_subplot(2, n_samples, n_samples + i + 1, projection='3d')
            ax2.scatter(sample['surface'][:, 0], sample['surface'][:, 1],
                       sample['surface'][:, 2], s=0.3, c='steelblue', alpha=0.3,
                       label='Surface')
            ax2.scatter(pred_np[:, 0], pred_np[:, 1], pred_np[:, 2],
                       s=0.5, c='green', alpha=0.5, label='Interior (Pred)')
            ax2.set_title(f'Generated (Predicted)', fontsize=9)
            ax2.legend(fontsize=6)

        fig.suptitle('Generated vs Ground Truth Interior Nodes',
                     fontsize=14, fontweight='bold')
        plt.tight_layout()
        plt.savefig('generated_vs_gt.png', dpi=CONFIG['fig_dpi'], bbox_inches='tight')
        plt.show()

    @staticmethod
    def plot_quality_comparison(fold_results):
        """Compare generated mesh quality across folds."""
        fig, axes = plt.subplots(1, 3, figsize=(15, 5))
        fig.suptitle('Generated Mesh Quality', fontsize=14, fontweight='bold')

        all_ars, all_sjs, all_goods = [], [], []
        for fr in fold_results:
            for m in fr.get('all_metrics', []):
                if 'mean_aspect_ratio' in m:
                    all_ars.append(m['mean_aspect_ratio'])
                    all_sjs.append(m['mean_scaled_jacobian'])
                    all_goods.append(m.get('pct_good', 0))

        if all_ars:
            axes[0].hist(all_ars, bins=20, color='steelblue', edgecolor='white')
            axes[0].axvline(CONFIG['ar_good'], color='green', ls='--')
            axes[0].set_xlabel('Mean Aspect Ratio')
            axes[0].set_title('Aspect Ratio (Generated)')

            axes[1].hist(all_sjs, bins=20, color='teal', edgecolor='white')
            axes[1].axvline(CONFIG['sj_good'], color='green', ls='--')
            axes[1].set_xlabel('Mean Scaled Jacobian')
            axes[1].set_title('Scaled Jacobian (Generated)')

            axes[2].hist(all_goods, bins=20, color='#2ecc71', edgecolor='white')
            axes[2].set_xlabel('% Good Quality Elements')
            axes[2].set_title('Quality Distribution')

        plt.tight_layout()
        plt.savefig('quality_comparison.png', dpi=CONFIG['fig_dpi'], bbox_inches='tight')
        plt.show()


# ============================================================
# SECTION 16: MAIN PIPELINE (COMPLETE)
# ============================================================
def run_pipeline(skip_training=False):
    """
    Complete end-to-end pipeline:
    Phase 1: Parse, analyze, visualize CDB meshes
    Phase 2: Prepare dataset for AI training
    Phase 3: Train and evaluate mesh generation model
    """
    print("\n" + "=" * 70)
    print("🦴 TETRAHEDRAL MESH — AI-Based Mesh Generation for Femur")
    print("   Surface → Volume Mesh | DGCNN Encoder + CVAE Decoder")
    print("=" * 70)

    # Mount Drive
    try:
        from google.colab import drive
        drive.mount('/content/drive')
        print("✅ Google Drive mounted")
    except ImportError:
        print("ℹ️ Not on Colab")

    # ══════════════════════════════════════════════════════════
    # PHASE 1: Data Analysis
    # ══════════════════════════════════════════════════════════
    print("\n" + "=" * 60)
    print("📂 PHASE 1: Parsing & Analyzing CDB Files")
    print("=" * 60)

    parser = CDBParser()
    all_data = parser.parse_directory(CONFIG['data_dir'])
    if not all_data:
        print("❌ No data found.")
        return

    # Validate
    for fname, data in list(all_data.items())[:3]:
        result, _ = TetrahedralMeshAnalyzer.validate_mesh(
            data['nodes_df'], data['elements'])
        print(f"  {fname}: {result['valid_elements']}/{result['total_elements']} valid")

    # Quality metrics
    all_quality = {}
    for fname, data in all_data.items():
        qdf = MeshQualityAnalyzer.compute_all_metrics(data['nodes_df'], data['elements'])
        if not qdf.empty:
            all_quality[fname] = qdf

    # Surface extraction
    all_surfaces = {}
    for fname, data in all_data.items():
        sn, sf, ss = SurfaceExtractor.get_surface_mesh(data['nodes_df'], data['elements'])
        all_surfaces[fname] = {'nodes_df': sn, 'faces': sf, 'stats': ss}

    # Visualize sample
    sample = list(all_data.keys())[0]
    sd, sf = all_data[sample], all_surfaces[sample]
    MeshVisualizer.plot_surface_vs_tetrahedral(
        sd['nodes_df'], sd['elements'], sf['faces'], sample)
    if sample in all_quality:
        MeshVisualizer.plot_quality_distribution(all_quality[sample],
                                                  title=f"GT Quality: {sample}")

    # Dataset overview
    stats_df = DatasetAnalyzer.analyze_dataset(all_data)
    DatasetAnalyzer.plot_overview(stats_df)

    if skip_training:
        print("\n⏩ Skipping training (skip_training=True)")
        return all_data, all_quality, all_surfaces, stats_df

    # ══════════════════════════════════════════════════════════
    # PHASE 2 & 3: AI Training & Evaluation
    # ══════════════════════════════════════════════════════════
    print("\n" + "=" * 60)
    print("🧠 PHASE 2-3: Training Mesh Generation Model")
    print("  Architecture: DGCNN Encoder + Conditional VAE Decoder")
    print("  Task: Surface → Interior Node Prediction")
    print("=" * 60)

    fold_results = run_kfold_training(all_data)

    # Visualize results
    ResultsVisualizer.plot_training_curves(fold_results)
    ResultsVisualizer.plot_quality_comparison(fold_results)

    # Show generated vs GT for best fold
    best_fold = min(fold_results, key=lambda r: r['mean_chamfer'])
    print(f"\n  Best fold: {best_fold['fold']} "
          f"(CD={best_fold['mean_chamfer']:.6f})")

    print("\n" + "=" * 70)
    print("📋 COMPLETE PIPELINE FINISHED")
    print("=" * 70)
    print(f"""
  📂 Dataset: {len(all_data)} CDB files
  🧠 Model:   DGCNN Encoder + CVAE Decoder (DefTet-inspired)
  📊 Results:
     Chamfer Distance: {np.mean([r['mean_chamfer'] for r in fold_results]):.6f}
    """)

    return all_data, all_quality, all_surfaces, stats_df, fold_results


# ============================================================
# RUN
# ============================================================
if __name__ == '__main__':
    # Phase 1 only (analysis): run_pipeline(skip_training=True)
    # Full pipeline (analysis + training): run_pipeline()
    results = run_pipeline()
